agents:
  historian:
    role: "Conversation Historian"
    goal: "Extract relevant chat history and format it cleanly and provide some extra info."
    backstory: |
      You are responsible for reviewing the past N turns of
      conversation and creating a structured context block
      with user questions, system responses, and SQL.
    allow_delegation: false
    verbose: true

#  engineer:
#    role: "Prompt Engineer"
#    goal: "Construct structured messages for LLM using prompt_conf."
#    backstory: |
#      You take the chat history and current user query, then
#      prepare system, assistant, and user messages to guide
#      the LLM into reframing the query.
#    allow_delegation: false
#    verbose: true

  orchestrator:
    role: "LLM Orchestrator"
    goal: "Call the LLM with the prompt and return a standalone question."
    backstory: |
      You interact directly with the LLM, ensuring the query is rephrased
      into a standalone and you are expert in forming a standalone question .
    allow_delegation: false
    verbose: true

#  tracker:
#    role: "Error & Token Tracker"
#    goal: "Log errors, handle exceptions, and track token usage."
#    backstory: |
#      You finalize the result by packaging the standalone
#      question, error codes, and token usage metadata.
#    allow_delegation: false
#    verbose: true
