tasks:
  standalone_task:
    description: |
      Chat history:{chat_history}

      Current question:{question}

      Task: Rewrite the current question into a standalone, self-contained question 
      that does rely on previous context.

    expected_output: "A single standalone question string."
    agent: standalone_agent
